"""Unit test module for AISPayloadInfo.mid.

Typical Usage:
    python -m test                                           # Run *all* the test cases
    python -m test.unit_test                                 # Run *all* the unit test cases
    python -m test.unit_test.test_ais                        # Run *all* ais sub-package test cases
    python -m test.unit_test.test_ais.test_ais_payload_info  # Run *all* AISPayloadInfo method tests
    # Run just these unit tests
    python -m test.unit_test.test_ais.test_ais_payload_info.test_ais_payload_info_mid
    # Run just this normal 1 unit test
    python -m test.unit_test.test_ais.test_ais_payload_info.test_ais_payload_info_mid -k n01
"""

# Standard Imports
from typing import Any
# Third Party Imports
from tediousstart.tediousstart import execute_test_cases
# Local Imports
from gallant_input.ais.exceptions import AISPayloadInvalid
from gallant_input.ais.payload_info import AISPayloadInfo
from gallant_input.converters import convert_int_to_bin_bytes
from test.unit_test.test_ais.test_ais_payload_info import AISPayloadInfoUnitTest


class AISPayloadInfoMidUnitTest(AISPayloadInfoUnitTest):
    """Parent class for all AISPayloadInfo.mid unit tests.

    Attributes:
        input_ap_bin_bytes:  # Test case input: AISPayload(bin_bytes)
        test_case_data:      # Stores data about the test case as a TestCaseData object
        test_input_dir:      # Default input directory (OPTIONAL)
        test_output_dir:     # Default output directory (OPTIONAL)
    """

    # CORE CLASS METHODS
    # Methods listed in call order

    def call_callable(self):
        """Defines how the class will invoke the function call.

        Child class must override this method.  See TediousUnitTest.call_callable() for details.
        """
        test_obj = self.create_aispayloadinfo(*self._args, **self._kwargs)
        return test_obj.mid

    def validate_return_value(self, return_value):
        """Defines how the class will validate the return value of the tested call."""
        self._validate_return_value(return_value=return_value)

    # COMMON-USE METHODS
    # Methods listed in alphabetical order

    # CLASS HELPER METHODS
    # Methods listed in alphabetical order

    def run_test_exception(self, exception_type: Exception, exception_msg: str) -> None:
        """Common method calls for a test case expected to raise an exception.

        Test author must call self.set_test_input() before calling this method.

        Args:
            exception_type: An Exception type to expect (e.g., ValueError).
            exception_msg: A sub-string, empty or not, to look for in the raised Exception.
        """
        self.expect_exception(exception_type=exception_type, exception_msg=exception_msg)
        self.run_test()

    def run_test_input_exception(self, test_input: Any, exception_type: Exception,
                                 exception_msg: str) -> None:
        """Common method calls for a test case expected to raise an exception.

        Args:
            test_input: The AISPayloadInfo() argument.
            exception_type: An Exception type to expect (e.g., ValueError).
            exception_msg: A sub-string, empty or not, to look for in the raised Exception.
        """
        self.set_test_input(test_input)
        self.run_test_exception(exception_type=exception_type, exception_msg=exception_msg)

    def run_test_input_return(self, test_input: bytes, exp_return: int) -> None:
        """Common method calls for a test case expected to return.

        Args:
            test_input: Well-formed AIS payload as a binary bytes string to use as the
                AISPayloadInfo() argument.
            exp_return: The expected value of AISPayloadInfo.mid.
        """
        self.set_test_input(test_input)
        self.run_test_return(exp_return=exp_return)

    def run_test_return(self, exp_return: int) -> None:
        """Common method calls for a test case expected to return.

        Test author must set test input before caling this method.

        Args:
            exp_return: The expected value of AISPayloadInfo.mid.
        """
        self.expect_return(exp_return)
        self.run_test()

    def set_mmsi_test_input(self, mmsi: Any) -> None:
        """Set granular test input using self.GOOD_AIS_PAYLOAD1 as default input but mmsi is bad."""
        msg_type = self.GOOD_AIS_PAYLOAD1[0:6]
        repeat = self.GOOD_AIS_PAYLOAD1[6:8]
        msg_bits = self.GOOD_AIS_PAYLOAD1[38:]
        self.set_test_input(msg_type=msg_type, repeat=repeat, mmsi=mmsi, msg_bits=msg_bits)


class NormalAISPayloadInfoMidUnitTest(AISPayloadInfoMidUnitTest):
    """Normal Test Cases."""

    def test_n01_ais_repo_default(self):
        """Valid AIS payload generated by code from TrendMicro's ais repo.

        See: https://github.com/trendmicro/ais
        """
        test_input = self.GOOD_AIS_PAYLOAD1
        exp_return = 247
        self.run_test_input_return(test_input, exp_return)

    def test_n02_repo_generated_payload(self):
        """Valid AIS payload generated by code from TrendMicro's ais repo.

        See: https://github.com/trendmicro/ais
        """
        test_input = self.GOOD_AIS_PAYLOAD2
        exp_return = 740
        self.run_test_input_return(test_input, exp_return)


class BoundaryAISPayloadInfoMidUnitTest(AISPayloadInfoMidUnitTest):
    """Boundary Test Cases."""

    def __init__(self, *args, **kwargs) -> None:
        """AISUnitTest ctor."""
        # ATTRIBUTES
        super().__init__(*args, **kwargs)

        self.good_ais_payload1_mmsi = self.GOOD_AIS_PAYLOAD1[8:38]  # GOOD_AIS_PAYLOAD1's MMSI

    def call_callable(self):
        """Overriding parent method for added granularity."""
        test_obj = AISPayloadInfo(*self._args, **self._kwargs)
        return test_obj.mid

    def test_b01_too_short_empty(self):
        """Invalid mmsi length: 0."""
        test_input = self.good_ais_payload1_mmsi[0:0]
        exp_except = ValueError
        exp_except_msg = 'The "mmsi" argument must be of length "30" '
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)

    def test_b02_too_short_one(self):
        """Invalid mmsi length: 1."""
        test_input = self.good_ais_payload1_mmsi[0:1]
        exp_except = ValueError
        exp_except_msg = 'The "mmsi" argument must be of length "30" '
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)

    def test_b03_too_short_minus_one(self):
        """Invalid mmsi length: 30-1."""
        test_input = self.good_ais_payload1_mmsi[0:30-1]
        exp_except = ValueError
        exp_except_msg = 'The "mmsi" argument must be of length "30" '
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)

    def test_b04_too_long_plus_one(self):
        """Invalid mmsi length: 30+1."""
        test_input = (self.good_ais_payload1_mmsi * 2)[0:30+1]
        exp_except = ValueError
        exp_except_msg = 'The "mmsi" argument must be of length "30" '
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)

    def test_b05_too_long_double(self):
        """Invalid mmsi length: 30*2."""
        test_input = self.good_ais_payload1_mmsi * 2
        exp_except = ValueError
        exp_except_msg = 'The "mmsi" argument must be of length "30" '
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)

    def test_b06_barely_bad_mmsi_conversion(self):
        """Bad MMSI binary value converts to 1000000000 (which is too long for a valid MMSI)."""
        test_input = b'111011100110101100101000000000'  # 1,000,000,000
        exp_except = AISPayloadInvalid
        exp_except_msg = 'Invalid MMSI length of '
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)


class ErrorAISPayloadInfoMidUnitTest(AISPayloadInfoMidUnitTest):
    """Error Test Cases."""

    def call_callable(self):
        """Overriding parent method for added granularity."""
        test_obj = AISPayloadInfo(*self._args, **self._kwargs)
        return test_obj.mid

    def test_e01_bad_ctor_data_type_string(self):
        """Bad ctor 'mmsi' input: string data type."""
        test_input = self.GOOD_AIS_PAYLOAD1[8:38].decode('ascii')  # Good input, bad data type
        exp_except = TypeError
        exp_except_msg = 'argument should have been of type '
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)

    def test_e02_bad_ctor_data_type_none(self):
        """Bad ctor input: None data type."""
        test_input = None
        exp_except = TypeError
        exp_except_msg = 'argument should have been of type '
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)

    def test_e03_bad_ctor_value_decimal(self):
        """Bad ctor input: Decimal value instead of binary."""
        test_input = b'000000000000000000000247320162'
        exp_except = ValueError
        exp_except_msg = 'Invalid binary value detected in "mmsi"'
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)


class SpecialAISPayloadInfoMidUnitTest(AISPayloadInfoMidUnitTest):
    """Special Test Cases."""

    def call_callable(self):
        """Overriding parent method for added granularity."""
        test_obj = AISPayloadInfo(*self._args, **self._kwargs)
        return test_obj.mid

    def test_s01_bad_payload_all_zeroes(self):
        """Obviously bad AIS payload: all zeroes."""
        test_input = b'0' * 30
        exp_except = AISPayloadInvalid
        exp_except_msg = 'Unable to locate MID: '
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)

    def test_s02_bad_payload_all_ones(self):
        """Obviously bad AIS payload: all zeroes."""
        test_input = b'1' * 30
        exp_except = AISPayloadInvalid
        exp_except_msg = 'Invalid MMSI length of '
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_exception(exp_except, exp_except_msg)

    def test_s03_non_ship_mmsi_divers_radio(self):
        """Valid AIS payload with a non-standard MMSI format: 8MIDXXXXX.

        Diver’s radio (not used in the U.S. in 2013).

        See: https://www.e-navigation.nl/content/mmsi-mid-formats
        """
        mmsi = '836610101'  # https://www.marinetraffic.com/en/ais/details/ships/shipid:7281226
        test_input = convert_int_to_bin_bytes(number=int(mmsi), min_width=30)
        exp_return = int(mmsi[1:4])
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_return(exp_return)

    def test_s04_non_ship_mmsi_group_of_ships(self):
        """Valid AIS payload with a non-standard MMSI format: 0MIDXXXXX.

        Group of ships; the U.S. Coast Guard, for example, is 03699999.

        See: https://www.e-navigation.nl/content/mmsi-mid-formats
        """
        # https://beacons.amsa.gov.au/mmsi/index.asp
        mmsi = '050312345'  # MMSI Formats --> Group MMSIs --> Ex. 1
        test_input = convert_int_to_bin_bytes(number=int(mmsi), min_width=30)
        exp_return = int(mmsi[0:3])
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_return(exp_return)

    def test_s05_non_ship_mmsi_coastal_station(self):
        """Valid AIS payload with a non-standard MMSI format: 00MIDXXXX.

        Coastal stations.

        See: https://www.e-navigation.nl/content/mmsi-mid-formats
        """
        mmsi = '3669999'  # https://www.marinetraffic.com/en/ais/details/ships/shipid:4224109
        test_input = convert_int_to_bin_bytes(number=int(mmsi), min_width=30)
        exp_return = int(mmsi[0:3])
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_return(exp_return)

    def test_s06_non_ship_mmsi_sar_aircraft(self):
        """Valid AIS payload with a non-standard MMSI format: 111MIDXXX.

        SAR (Search and Rescue) aircraft.

        See: https://www.e-navigation.nl/content/mmsi-mid-formats
        """
        mmsi = '111316001'  # https://www.marinetraffic.com/en/ais/details/ships/shipid:5685588
        test_input = convert_int_to_bin_bytes(number=int(mmsi), min_width=30)
        exp_return = int(mmsi[3:6])
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_return(exp_return)

    def test_s07_non_ship_mmsi_navigation_aid(self):
        """Valid AIS payload with a non-standard MMSI format: 99MIDXXXX.

        Aids to Navigation.

        See: https://www.e-navigation.nl/content/mmsi-mid-formats
        """
        mmsi = '992320001'  # https://www.marinetraffic.com/en/ais/details/ships/shipid:5602084
        test_input = convert_int_to_bin_bytes(number=int(mmsi), min_width=30)
        exp_return = int(mmsi[2:5])
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_return(exp_return)

    def test_s08_non_ship_mmsi_auxiliary_craft(self):
        """Valid AIS payload with a non-standard MMSI format: 98MIDXXXX.

        Auxiliary craft associated with a parent ship.

        See: https://www.e-navigation.nl/content/mmsi-mid-formats
        """
        mmsi = '983669046'  # https://www.marinetraffic.com/en/ais/details/ships/shipid:10255197
        test_input = convert_int_to_bin_bytes(number=int(mmsi), min_width=30)
        exp_return = int(mmsi[2:5])
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_return(exp_return)

    def test_s09_non_ship_mmsi_ais_sart(self):
        """Valid AIS payload with a non-standard MMSI format: 970MIDXXX.

        AIS SART (Search and Rescue Transmitter).

        See: https://www.e-navigation.nl/content/mmsi-mid-formats
        """
        mmsi = '970360781'  # https://www.marinetraffic.com/en/ais/details/ships/shipid:8796138
        test_input = convert_int_to_bin_bytes(number=int(mmsi), min_width=30)
        exp_return = int(mmsi[3:6])
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_return(exp_return)

    def test_s10_non_ship_mmsi_mob_device(self):
        """Valid AIS payload with a non-standard MMSI format: 972XXXXXX.

        MOB (Man Overboard) device.

        See: https://www.e-navigation.nl/content/mmsi-mid-formats
        """
        mmsi = '972367686'  # https://www.marinetraffic.com/en/ais/details/ships/shipid:9069228
        test_input = convert_int_to_bin_bytes(number=int(mmsi), min_width=30)
        exp_return = int(mmsi[3:6])
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_return(exp_return)

    def test_s11_non_ship_mmsi_epirb_ais(self):
        """Valid AIS payload with a non-standard MMSI format: 974XXXXXX.

        EPIRB (Emergency Position Indicating Radio Beacon) AIS.

        See: https://www.e-navigation.nl/content/mmsi-mid-formats
        """
        mmsi = '974209718'  # https://www.marinetraffic.com/en/ais/details/ships/shipid:9070804
        test_input = convert_int_to_bin_bytes(number=int(mmsi), min_width=30)
        exp_return = int(mmsi[3:6])
        self.set_mmsi_test_input(mmsi=test_input)
        self.run_test_return(exp_return)


if __name__ == '__main__':
    execute_test_cases()
